
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed5;
	
	private global::Gtk.Image queenBeeImage;
	
	private global::Gtk.Image darkKnightImage;
	
	private global::Gtk.Image vampireImage;
	
	private global::Gtk.Image zombieImage;
	
	private global::Gtk.Image malboroImage;
	
	private global::Gtk.Image goblinImage;
	
	private global::Gtk.Image impImage;
	
	private global::Gtk.Image killerFishImage;
	
	private global::Gtk.Image wizardImage;
	
	private global::Gtk.Image dragonImage;
	
	private global::Gtk.Label monsterLabel;
	
	private global::Gtk.Label hpLabel;
	
	private global::Gtk.Label mpLabel;
	
	private global::Gtk.Label rcLabel;
	
	private global::Gtk.Label hp2Label;
	
	private global::Gtk.Label mp2Label;
	
	private global::Gtk.Label rc2Label;
	
	private global::Gtk.Label moveLabel;
	
	private global::Gtk.Button moveButton;
	
	private global::Gtk.ComboBox combobox1;
	
	private global::Gtk.Label damagePLabel;
	
	private global::Gtk.Label damageLabel;
	
	private global::Gtk.Label use2Label;
	
	private global::Gtk.Label damageELabel;
	
	private global::Gtk.Label useLabel;
	
	private global::Gtk.Label damageE2Label;
	
	private global::Gtk.Label damageP2Label;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("WWG v 2.0");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.AllowShrink = true;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed5 = new global::Gtk.Fixed ();
		this.fixed5.Name = "fixed5";
		this.fixed5.HasWindow = false;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.queenBeeImage = new global::Gtk.Image ();
		this.queenBeeImage.Name = "queenBeeImage";
		this.queenBeeImage.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("WWG.Images.queenBee.png");
		this.fixed5.Add (this.queenBeeImage);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.queenBeeImage]));
		w1.X = 85;
		w1.Y = 50;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.darkKnightImage = new global::Gtk.Image ();
		this.darkKnightImage.Name = "darkKnightImage";
		this.darkKnightImage.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("WWG.Images.darkKnight.png");
		this.fixed5.Add (this.darkKnightImage);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.darkKnightImage]));
		w2.X = 85;
		w2.Y = 50;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.vampireImage = new global::Gtk.Image ();
		this.vampireImage.Name = "vampireImage";
		this.vampireImage.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("WWG.Images.vampire.png");
		this.fixed5.Add (this.vampireImage);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.vampireImage]));
		w3.X = 85;
		w3.Y = 50;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.zombieImage = new global::Gtk.Image ();
		this.zombieImage.Name = "zombieImage";
		this.zombieImage.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("WWG.Images.zombie.png");
		this.fixed5.Add (this.zombieImage);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.zombieImage]));
		w4.X = 85;
		w4.Y = 50;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.malboroImage = new global::Gtk.Image ();
		this.malboroImage.Name = "malboroImage";
		this.malboroImage.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("WWG.Images.malboro.png");
		this.fixed5.Add (this.malboroImage);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.malboroImage]));
		w5.X = 85;
		w5.Y = 50;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.goblinImage = new global::Gtk.Image ();
		this.goblinImage.Name = "goblinImage";
		this.goblinImage.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("WWG.Images.goblin.png");
		this.fixed5.Add (this.goblinImage);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.goblinImage]));
		w6.X = 85;
		w6.Y = 50;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.impImage = new global::Gtk.Image ();
		this.impImage.Name = "impImage";
		this.impImage.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("WWG.Images.imp.png");
		this.fixed5.Add (this.impImage);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.impImage]));
		w7.X = 85;
		w7.Y = 50;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.killerFishImage = new global::Gtk.Image ();
		this.killerFishImage.Name = "killerFishImage";
		this.killerFishImage.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("WWG.Images.killerFish.png");
		this.fixed5.Add (this.killerFishImage);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.killerFishImage]));
		w8.X = 85;
		w8.Y = 50;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.wizardImage = new global::Gtk.Image ();
		this.wizardImage.Name = "wizardImage";
		this.wizardImage.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("WWG.Images.wizard.png");
		this.fixed5.Add (this.wizardImage);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.wizardImage]));
		w9.X = 85;
		w9.Y = 50;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.dragonImage = new global::Gtk.Image ();
		this.dragonImage.Name = "dragonImage";
		this.dragonImage.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("WWG.Images.dragon.png");
		this.fixed5.Add (this.dragonImage);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.dragonImage]));
		w10.X = 85;
		w10.Y = 50;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.monsterLabel = new global::Gtk.Label ();
		this.monsterLabel.Name = "monsterLabel";
		this.monsterLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("-- monster --");
		this.fixed5.Add (this.monsterLabel);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.monsterLabel]));
		w11.X = 185;
		w11.Y = 65;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.hpLabel = new global::Gtk.Label ();
		this.hpLabel.Name = "hpLabel";
		this.hpLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("HP:");
		this.fixed5.Add (this.hpLabel);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.hpLabel]));
		w12.X = 33;
		w12.Y = 173;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.mpLabel = new global::Gtk.Label ();
		this.mpLabel.Name = "mpLabel";
		this.mpLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("MP:");
		this.fixed5.Add (this.mpLabel);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.mpLabel]));
		w13.X = 33;
		w13.Y = 203;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.rcLabel = new global::Gtk.Label ();
		this.rcLabel.Name = "rcLabel";
		this.rcLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("RC:");
		this.fixed5.Add (this.rcLabel);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.rcLabel]));
		w14.X = 33;
		w14.Y = 233;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.hp2Label = new global::Gtk.Label ();
		this.hp2Label.Name = "hp2Label";
		this.hp2Label.LabelProp = global::Mono.Unix.Catalog.GetString ("--");
		this.fixed5.Add (this.hp2Label);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.hp2Label]));
		w15.X = 65;
		w15.Y = 173;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.mp2Label = new global::Gtk.Label ();
		this.mp2Label.Name = "mp2Label";
		this.mp2Label.LabelProp = global::Mono.Unix.Catalog.GetString ("--");
		this.fixed5.Add (this.mp2Label);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.mp2Label]));
		w16.X = 65;
		w16.Y = 203;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.rc2Label = new global::Gtk.Label ();
		this.rc2Label.Name = "rc2Label";
		this.rc2Label.LabelProp = global::Mono.Unix.Catalog.GetString ("--");
		this.fixed5.Add (this.rc2Label);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.rc2Label]));
		w17.X = 65;
		w17.Y = 233;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.moveLabel = new global::Gtk.Label ();
		this.moveLabel.Name = "moveLabel";
		this.moveLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("choose move:");
		this.fixed5.Add (this.moveLabel);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.moveLabel]));
		w18.X = 225;
		w18.Y = 170;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.moveButton = new global::Gtk.Button ();
		this.moveButton.CanFocus = true;
		this.moveButton.Name = "moveButton";
		this.moveButton.UseUnderline = true;
		this.moveButton.Label = global::Mono.Unix.Catalog.GetString ("Use ->");
		this.fixed5.Add (this.moveButton);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.moveButton]));
		w19.X = 225;
		w19.Y = 205;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.combobox1 = global::Gtk.ComboBox.NewText ();
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("Use spell!"));
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("Use sword!"));
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("Use HP potion!"));
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("Use MP potion!"));
		this.combobox1.Name = "combobox1";
		this.combobox1.Active = 0;
		this.fixed5.Add (this.combobox1);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.combobox1]));
		w20.X = 280;
		w20.Y = 205;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.damagePLabel = new global::Gtk.Label ();
		this.damagePLabel.Name = "damagePLabel";
		this.damagePLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("p:");
		this.fixed5.Add (this.damagePLabel);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.damagePLabel]));
		w21.X = 325;
		w21.Y = 65;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.damageLabel = new global::Gtk.Label ();
		this.damageLabel.Name = "damageLabel";
		this.damageLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("damage:");
		this.fixed5.Add (this.damageLabel);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.damageLabel]));
		w22.X = 325;
		w22.Y = 40;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.use2Label = new global::Gtk.Label ();
		this.use2Label.Name = "use2Label";
		this.use2Label.LabelProp = global::Mono.Unix.Catalog.GetString ("e move .....");
		this.fixed5.Add (this.use2Label);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.use2Label]));
		w23.X = 35;
		w23.Y = 20;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.damageELabel = new global::Gtk.Label ();
		this.damageELabel.Name = "damageELabel";
		this.damageELabel.LabelProp = global::Mono.Unix.Catalog.GetString ("e:");
		this.fixed5.Add (this.damageELabel);
		global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.damageELabel]));
		w24.X = 325;
		w24.Y = 90;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.useLabel = new global::Gtk.Label ();
		this.useLabel.Name = "useLabel";
		this.useLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("p move .....");
		this.fixed5.Add (this.useLabel);
		global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.useLabel]));
		w25.X = 225;
		w25.Y = 245;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.damageE2Label = new global::Gtk.Label ();
		this.damageE2Label.Name = "damageE2Label";
		this.damageE2Label.LabelProp = global::Mono.Unix.Catalog.GetString (".....");
		this.fixed5.Add (this.damageE2Label);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.damageE2Label]));
		w26.X = 350;
		w26.Y = 90;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.damageP2Label = new global::Gtk.Label ();
		this.damageP2Label.Name = "damageP2Label";
		this.damageP2Label.LabelProp = global::Mono.Unix.Catalog.GetString (".....");
		this.fixed5.Add (this.damageP2Label);
		global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.damageP2Label]));
		w27.X = 350;
		w27.Y = 65;
		this.Add (this.fixed5);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 443;
		this.DefaultHeight = 323;
		this.queenBeeImage.Hide ();
		this.darkKnightImage.Hide ();
		this.vampireImage.Hide ();
		this.zombieImage.Hide ();
		this.malboroImage.Hide ();
		this.goblinImage.Hide ();
		this.impImage.Hide ();
		this.killerFishImage.Hide ();
		this.wizardImage.Hide ();
		this.dragonImage.Hide ();
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.moveButton.Clicked += new global::System.EventHandler (this.OnMoveButtonClicked);
	}
}
